name: Docker build

on:
  # Triggered from frappe/frappe and frappe/erpnext on releases
  repository_dispatch:
    types: [ build-docker ]
  workflow_dispatch:

jobs:
  build-docker-image:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      repo: erpnext
      version: "develop"
      push: true
      python_version: 3.11.6
      node_version: 18.18.2
      frappe_version: ${{ github.event.client_payload.frappe-version }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  deploy-k8s:
    name: Deploy to k8s
    runs-on: ubuntu-22.04
    needs: build-docker-image
    steps:
      - name: Deploy to K8s (Dry - Run)
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
          IMAGE_TAG: ${{needs.build-docker-image.outputs.imageTag}}
        with:
          args: |
            helm version
            helm upgrade --install ${{ secrets.HELM_RELEASE_NAME }} ${{ secrets.HELM_CHART }} -n ${{ secrets.HELM_RELEASE_NAMESPACE }} --version ${{ secrets.HELM_RELEASE_VERSION }} --repo ${{ secrets.HELM_REPO }} --reuse-values --dry-run --set image.tag=$IMAGE_TAG

      - name: Deploy to K8s
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
          IMAGE_TAG: ${{needs.build-docker-image.outputs.imageTag}}
        with:
          args: |
            helm upgrade --install ${{ secrets.HELM_RELEASE_NAME }} ${{ secrets.HELM_CHART }} -n ${{ secrets.HELM_RELEASE_NAMESPACE }} --version ${{ secrets.HELM_RELEASE_VERSION }} --repo ${{ secrets.HELM_REPO }} --reuse-values --set image.tag=$IMAGE_TAG

