name: Docker build

on:
  # Triggered from frappe/frappe and frappe/erpnext on releases
  repository_dispatch:
    types: [build-docker]
  workflow_dispatch:

jobs:
  v14:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      repo: erpnext
      version: "14"
      push: ${{ github.repository == 'frappe/frappe_docker' && github.event_name != 'pull_request' }}
      python_version: 3.10.13
      node_version: 16.20.2
      docker_tag:  ${{ github.event.client_payload.gh-docker-tag }}
      frappe_version:  ${{ github.event.client_payload.frappe-version }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
