name: Build

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
        description: "'erpnext' or 'frappe'"
      version:
        required: true
        type: string
        description: "Major version, git tags should match 'v{version}.*'; or 'develop'"
      push:
        required: true
        type: boolean
      python_version:
        required: true
        type: string
        description: Python Version
      node_version:
        required: true
        type: string
        description: NodeJS Version
      frappe_version:
        required: false
        type: string
        description: Frappe version
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
    outputs:
      imageTag:
        description: "Image tags"
        value: ${{ jobs.build.outputs.imageTag }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      imageTag: ${{ steps.args.outputs.ERPNEXT_DOCKER_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Get latest versions
        run: python3 ./.github/scripts/get_latest_hash.py --version ${{ inputs.version }}

      - name: Set build args
        id: args
        run: |
          echo "PYTHON_VERSION=${{ inputs.python_version }}" >> "$GITHUB_ENV"
          echo "NODE_VERSION=${{ inputs.node_version }}" >> "$GITHUB_ENV"
          echo "FRAPPE_VERSION=${{ inputs.frappe_version }}" >> "$GITHUB_ENV"
          echo "ERPNEXT_VERSION=${{ inputs.frappe_version }}" >> "$GITHUB_ENV"
          echo "ERPNEXT_DOCKER_TAG=${{ inputs.frappe_version }}_f_${FRAPPE_VERSION}_e_${ERPNEXT_VERSION}" >> "$GITHUB_ENV"
          echo "ERPNEXT_DOCKER_TAG=${{ inputs.frappe_version }}_f_${FRAPPE_VERSION}_e_${ERPNEXT_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: registry.vngcloud.vn
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/bake-action@v4.0.0
        with:
          push: ${{ inputs.push }}
